server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Ride Service
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - name: CircuitBreaker
              args:
                name: rideServiceCB
                fallbackUri: forward:/fallback/ride-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        # Booking Service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingServiceCB
                fallbackUri: forward:/fallback/booking-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        # Payment Service
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCB
                fallbackUri: forward:/fallback/payment-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        # Rating Service
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingServiceCB
                fallbackUri: forward:/fallback/rating-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        # OpenAPI docs routes
        - id: ride-service-docs
          uri: lb://ride-service
          predicates:
            - Path=/v3/api-docs/ride-service
          filters:
            - RewritePath=/v3/api-docs/ride-service, /v3/api-docs

        - id: booking-service-docs
          uri: lb://booking-service
          predicates:
            - Path=/v3/api-docs/booking-service
          filters:
            - RewritePath=/v3/api-docs/booking-service, /v3/api-docs

        - id: payment-service-docs
          uri: lb://payment-service
          predicates:
            - Path=/v3/api-docs/payment-service
          filters:
            - RewritePath=/v3/api-docs/payment-service, /v3/api-docs

        - id: rating-service-docs
          uri: lb://rating-service
          predicates:
            - Path=/v3/api-docs/rating-service
          filters:
            - RewritePath=/v3/api-docs/rating-service, /v3/api-docs

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/carpooling}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/carpooling}/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Ride Service
        url: /v3/api-docs/ride-service
      - name: Booking Service
        url: /v3/api-docs/booking-service
      - name: Payment Service
        url: /v3/api-docs/payment-service
      - name: Rating Service
        url: /v3/api-docs/rating-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      rideServiceCB:
        baseConfig: default
      bookingServiceCB:
        baseConfig: default
      paymentServiceCB:
        baseConfig: default
        waitDurationInOpenState: 15s
      ratingServiceCB:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      rideServiceCB:
        baseConfig: default
      bookingServiceCB:
        baseConfig: default
      paymentServiceCB:
        baseConfig: default
        timeoutDuration: 5s
      ratingServiceCB:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.sawa.gateway: DEBUG
